### ISSUE TITLE
SMB/FTP support defining multiple shares

### ISSUE THREAD

**Issue by scriptingislife** [becksteadn/Bytes-Of-Swiss#32]
Create a YAML list with FTP/SMB shares then loop over them and add them to the config file.

```yaml
vars:
    sambashares:
      - name: public
        comment: Public resources
        path: /samba/public
        read_only: yes
        browsable: yes
      - name: private
        comment: Private resources
        path: /samba/private
        read_only: no
        browsable: no
```

http://scriptingis.life/cool-ansible-3/
